// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_h3VviEfk0j1h4cpy9LC2E-Zt8u0EkTU',
    appId: '1:821447961446:web:dcc0ed3af62966b7ae76a7',
    messagingSenderId: '821447961446',
    projectId: 'fir-learning-2-6069f',
    authDomain: 'fir-learning-2-6069f.firebaseapp.com',
    storageBucket: 'fir-learning-2-6069f.appspot.com',
    measurementId: 'G-8HX0GP0KPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAUAdbWHMh_WQPAanPL-IlB9bp1e9dejw',
    appId: '1:821447961446:android:6aa2a2b364603e22ae76a7',
    messagingSenderId: '821447961446',
    projectId: 'fir-learning-2-6069f',
    storageBucket: 'fir-learning-2-6069f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCemhuUPzhBtn3qDyHcQUER5ff2NR5Bk_Q',
    appId: '1:821447961446:ios:1dc409e681469385ae76a7',
    messagingSenderId: '821447961446',
    projectId: 'fir-learning-2-6069f',
    storageBucket: 'fir-learning-2-6069f.appspot.com',
    iosClientId: '821447961446-jb7t89m5bqh7d3cg3nikv5uu409qt6ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLearningPart2',
  );

}